apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: maddirrin104/netflix-clone-react-typescript:988c79d1331c0d7dfe3471633f38b9542605d694
          ports:
            - containerPort: 80